version: "3.9"

services:
  local_db:
    image: postgres:15
    restart: always
    ports:
      - "54320:5432"
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  postgresql-data:

networks:
  backend:
    driver: bridge